name: Compile Release
on:
  push:
    tags:
      - '*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - pio_env: gh_release
            artifact_name: firmware-x4_x3
          - pio_env: sticky
            artifact_name: firmware-sticky
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          enable-cache: false

      - name: Install PlatformIO Core
        run: uv pip install --system -U https://github.com/pioarduino/platformio-core/archive/refs/tags/v6.1.19.zip

      - name: Cache PlatformIO packages
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: pio-${{ runner.os }}-${{ hashFiles('platformio.ini') }}
          restore-keys: pio-${{ runner.os }}-

      - name: Build CrossPoint
        env:
          CROSSPOINT_RELEASE_BUILD: "1"
        run: pio run -e ${{ matrix.pio_env }} -j1

      - name: Name Release Firmware
        run: |
          cp ".pio/build/${{ matrix.pio_env }}/firmware.bin" \
            ".pio/build/${{ matrix.pio_env }}/${{ matrix.artifact_name }}.bin"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            .pio/build/${{ matrix.pio_env }}/bootloader.bin
            .pio/build/${{ matrix.pio_env }}/${{ matrix.artifact_name }}.bin
            .pio/build/${{ matrix.pio_env }}/firmware.elf
            .pio/build/${{ matrix.pio_env }}/firmware.map
            .pio/build/${{ matrix.pio_env }}/partitions.bin
